-- Safe, non-breaking analytics upgrade
-- Principles:
-- 1) Add-only changes
-- 2) New columns are nullable
-- 3) Existing runtime fields and constraints remain untouched

begin;

-- 1) Event warehouse table (new)
create table if not exists public.landing_page_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null,
  event_id text,
  event_source_url text,
  referer text,
  request_path text,
  user_agent text,
  ip_address text,
  fbp text,
  fbc text,
  fbclid text,
  test_event_code text,
  meta_pixel_id text,
  facebook_forward_status text,
  facebook_forward_error text,
  attribution jsonb,
  payload jsonb
);

create index if not exists idx_lpe_created_at
  on public.landing_page_events (created_at desc);

create index if not exists idx_lpe_event_name_created_at
  on public.landing_page_events (event_name, created_at desc);

create index if not exists idx_lpe_request_path_created_at
  on public.landing_page_events (request_path, created_at desc);

create index if not exists idx_lpe_fbclid
  on public.landing_page_events (fbclid)
  where fbclid is not null;

-- Optional but recommended: prevent anon reads/writes on raw event warehouse.
alter table public.landing_page_events enable row level security;

-- 2) Nullable extension fields on existing tables (add-only)
alter table public.songs
  add column if not exists tracking_config jsonb,
  add column if not exists routing_config jsonb,
  add column if not exists attribution_window_days integer;

alter table public.artists
  add column if not exists tracking_config jsonb,
  add column if not exists routing_config jsonb,
  add column if not exists attribution_window_days integer;

-- Soft guard: only validate if value provided
alter table public.songs
  drop constraint if exists songs_attribution_window_days_check;
alter table public.songs
  add constraint songs_attribution_window_days_check
  check (
    attribution_window_days is null
    or (attribution_window_days >= 1 and attribution_window_days <= 30)
  );

alter table public.artists
  drop constraint if exists artists_attribution_window_days_check;
alter table public.artists
  add constraint artists_attribution_window_days_check
  check (
    attribution_window_days is null
    or (attribution_window_days >= 1 and attribution_window_days <= 30)
  );

comment on table public.landing_page_events is
  'Raw landing-page event log for first-party attribution and platform-forwarding diagnostics.';

comment on column public.landing_page_events.facebook_forward_status is
  'Meta forward result: ok | error | skipped_missing_pixel | skipped_missing_token | skipped_no_event_name | skipped_internal_only.';

commit;
